name: build

on:
  pull_request:
    branches: [ master ]

env:
  RAILS_ENV: test
  BUNDLE_WITHOUT: development
  RAILS_MASTER_KEY: {{ your_test_master.key }}

jobs:
  bundle-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - uses: ruby/setup-ruby@v1
        if: ${{ contains(steps.files.outputs.modified, 'Gemfile.lock') }}
        with:
          bundler: 2.2.16
          bundler-cache: true

  specs:
    runs-on: ubuntu-latest
    needs: bundle-cache

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2.2.16
          bundler-cache: true

      - name: zeitwerk:check
        run: bundle exec rails zeitwerk:check

      - name: Setup DB
        run: bundle exec rails db:test:prepare

      - name: rspec
        run: bundle exec rspec

  lecturer-specs:
    runs-on: ubuntu-latest
    needs: bundle-cache

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup DB
        run: bundle exec rails db:test:prepare

      - name: Run FTP specs
        shell: bash
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          sudo apt-get install lftp
          lftp -c "open -u $FTP_USER,$FTP_PASS ftp.infinum.co; set ssl:verify-certificate no; get behaviour.tgz; bye"
          tar -xzvf behaviour.tgz
          source behaviour/profile
          lecturer-specs run-all $BRANCH_NAME
